apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xgsi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xgsi
    app.kubernetes.io/part-of: cin4s-839-0004-app
  name: devfile-sample-xgsi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xgsi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xgsi
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0004-tenant/cin4s-839-0004-app/devfile-sample-xgsi@sha256:0bd68ccdc08e450787cca906d93c883e924eef2e6b9e5e10d430eea80de826b3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
